apiVersion: v1
kind: ReplicaSet
metadata:
  name: first-rs
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello1
        image: tomcat
        ports:
        - containerPort: 8080
